#!/bin/bash

# Check if a folder path is provided
if [ -z "$1" ]; then
    echo "Usage: $0 /path/to/folder"
    exit 1
fi

# Ensure the given path is a directory
if [ ! -d "$1" ]; then
    echo "Error: '$1' is not a directory."
    exit 1
fi

# use nullglob in case there are no matching files
shopt -s nullglob

cover_art="cover.jpg"
baseline_art="baseline.jpg"
# arr=$(ls "$1")
arr=("$1"/*)
echo $arr

for file in "${arr[@]}"; do
    echo "Processing: $file"
    if [ ! -f "$cover_art" ]; then
      echo "Cover art not found"
      ffmpeg -i "$file" -an -vcodec copy "$cover_art" 
      jpegtran -outfile "$baseline_art" "$cover_art"
    fi

    echo "Updating metadata for $file"
    kid3-cli -c "set Picture:\"$baseline_art\" \"1\"" "$file"


    echo "Updated cover art for: $file"
done

# Cleanup
# rm -f "$cover_art" "$baseline_art"
echo "Processing complete."
